name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install CocoaPods
        run: bundle install

      - name: Install dependencies
        run: bundle exec pod install

      # - name: Build the app
      #   run: xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' clean build

      # - name: Run tests
      #   run: xcodebuild test -workspace MyApp.xcworkspace -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES

      # - name: Archive the app
      #   run: xcodebuild archive -workspace MyApp.xcworkspace -scheme MyApp -archivePath ${{ github.workspace }}/build/MyApp.xcarchive

      # - name: Export the archive
      #   run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/MyApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ${{ github.workspace }}/build

      # - name: Deploy to TestFlight
      #   env:
      #     APPLE_ID: ${{ secrets.APPLE_ID }}
      #     APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      #   run: |
      #     xcrun altool --upload-app --type ios -f ${{ github.workspace }}/build/MyApp.ipa -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD"
